### ISSUE TITLE
Desarrollo del algoritmo

### ISSUE THREAD

**Issue by lecepe00** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-caroacostatovany#3]
Desarrollo del algoritmo de optimización convexa.

**Comment by cecyar** [comment]
@Eduardo-Moreno Ya subí en la rama prog_cecy las primeras funciones que definimos. Chécalas y me avisas cualquier cosa :)

**Comment by Eduardo-Moreno** [comment]
> @Eduardo-Moreno Ya subí en la rama prog_cecy las primeras funciones que definimos. Chécalas y me avisas cualquier cosa :)
Las revisé y están todas OK

**Comment by lecepe00** [comment]
Se cierra issue con el método numérico finalizado.
